config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  get 'profile', action: :show, controller: 'users'
  post 'profile', action: :update, controller: 'users'
  get 'profile/edit', action: :edit, controller: 'users'
  # namespace :admin do
    resources :users, only: %i[index edit show update destroy]
    resources :events, only: %i[index edit show update destroy]
  # end
  resources :events do
    resources :attendances, only: %i[create new index]
  end
  resources :checkout, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  # after_create :confirm_send
  validates :start_date,
            presence: true,
            if: :start_date_cannot_be_in_the_past
  validates :duration,
            presence: true,
            numericality: { only_integer: true, greater_than: 0 },
            if: :not_multiple_of_five?
  validates :title,
            presence: true,
            length: { in: 5..140 }
  validates :description,
            presence: true,
            length: { in: 20..1001 }
  validates :price,
            presence: true,
            numericality: { only_integer: true, greater_than: 0, less_than: 1000 }
  validates :location, presence: true
  has_many :attendances
  belongs_to :admin, class_name: 'User'
  has_many :attendees, through: :attendances, source: :user
  has_one_attached :event_picture

  def confirm_send
    EventMailer.confirm_email(self).deliver_now
  end

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be in the past") if
      !start_date.blank? && start_date < Date.today
  end

  def not_multiple_of_five?
    errors.add(:duration, 'must be a multiple of 5') if
      !duration.blank? && duration % 5 != 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances
  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin_events_controller.rb
class AdminEventsController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :alert
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: %i[index]

  def index
    @event = Event.find(params[:event_id])
    @attendees = Attendance.where(event:@event)
    @count = Attendance.where(event:@event).count
  end

  def new
    @event = Event.find(params[:event_id])
  end

  def create
    # if payment == true
    #   redirect_to event_url(params[:id])
    # else
    #   render
    # end
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(current_user.id)
    @user.avatar.attach(params[:avatar])
    redirect_to(user_url(@user))
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    event = Event.find(params[:id])
    @session = Stripe::Checkout::Session.create(
      {
        mode: 'payment',
        success_url: root_url,
        cancel_url: root_url,
        payment_method_types: ['card'],
        line_items: [{
          quantity: 1,
          price_data: {
            currency: 'usd',
            unit_amount: event.price,
            product_data: {
              name: event.title
            }
          }
        }]
      }
    )
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :authenticate_user!, only: %i[new show create edit update]
  after_action :attend_new_event, only: [:create]

  def index
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(
      description: params[:description],
      start_date: params[:start_date],
      duration: params[:duration],
      location: params[:location],
      price: params[:price]
    )
      flash[:success] = 'You have successfully updated your event'
      redirect_to event_path(@event.id)
    else
      @event.errors.full_messages.each { |m| flash.now[:alert] = m }
      render edit_event_path(@event.id)
    end
  end

  def show
    @event = Event.find(params[:id])
    @count = Attendance.where(event_id: @event.id).count
    @attendance_possible = true
    @attendance_possible = false if Attendance.where(event_id:@event.id, user_id: current_user.id).count == 1
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(
      title: params[:event_title],
      description: params[:event_description],
      start_date: params[:event_start_date],
      duration: params[:event_duration],
      location: params[:event_location],
      price: params[:event_price],
      event_picture: params[:event_picture]
    )
    @event.admin = current_user
    if @event.save
      flash[:success] = 'You have successfully created a new event'
      redirect_to event_path(Event.last.id)
    else
      @event.errors.full_messages.each { |m| flash.now[:alert] = m }
      render new_event_path
    end
  end

  def destroy
    @event = Event.find_by_id(params[:id])
    @event.destroy
    flash[:success] = 'The gossip was destroyed'
    redirect_to events_path
  end

  private

  def attend_new_event
    @last_event = Event.last
    Attendance.create(event_id: @last_event.id, user_id: current_user.id)
  end

  # def authenticate_user!
  #   if current_user.admin
  #     flash[:success] = 'You are admin.'
  #     redirect_to admin_event_url
  #     redirect_to event_url
  #   else
  #     flash[:alert] = 'You need to be an admin to access this page.'
  #     redirect_to new_user_session_path
  #   end
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    log_out(current_user)
    flash.now[:info] = 'You logged out successfully'
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description]
    )
      if params[:avatar] != nil
        @user.avatar.attach(params[:avatar])
      end
      flash[:success] = 'User successfully updated!'
      redirect_to profile_path
    else
      @user.errors.full_messages.each { |m| flash.now[:alert] = m }
      render :edit
    end
  end

  def destroy

  end

  private

  def authenticate_user
    return if current_user

    flash[:alert] = 'Please log in.'
    redirect_to new_user_session_path
  end

end

app/helpers/admin_events_helper.rb
module AdminEventsHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(name)
    case name
    when 'notice' then 'alert alert-info text-center'
    when 'success' then 'alert alert-success alert-dismissable text-center'
    when 'error', 'alert', 'danger' then 'alert alert-danger alert-dismissable text-center'
    else
      'alert alert-primary'
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_events/destroy.html.erb
<h1>AdminEvents#destroy</h1>
<p>Find me in app/views/admin_events/destroy.html.erb</p>

app/views/admin_events/edit.html.erb
<h1>AdminEvents#edit</h1>
<p>Find me in app/views/admin_events/edit.html.erb</p>

app/views/admin_events/index.html.erb
<h1>AdminEvents#index</h1>
<p>Find me in app/views/admin_events/index.html.erb</p>

app/views/admin_events/show.html.erb
<h1>AdminEvents#show</h1>
<p>Find me in app/views/admin_events/show.html.erb</p>

app/views/admin_events/update.html.erb
<h1>AdminEvents#update</h1>
<p>Find me in app/views/admin_events/update.html.erb</p>

app/views/admin_users/destroy.html.erb
<h1>AdminUsers#destroy</h1>
<p>Find me in app/views/admin_users/destroy.html.erb</p>

app/views/admin_users/edit.html.erb
<h1>AdminUsers#edit</h1>
<p>Find me in app/views/admin_users/edit.html.erb</p>

app/views/admin_users/index.html.erb
<h1>AdminUsers#index</h1>
<p>Find me in app/views/admin_users/index.html.erb</p>

app/views/admin_users/show.html.erb
<h1>AdminUsers#show</h1>
<p>Find me in app/views/admin_users/show.html.erb</p>

app/views/admin_users/update.html.erb
<h1>AdminUsers#update</h1>
<p>Find me in app/views/admin_users/update.html.erb</p>

app/views/attendances/index.html.erb
<div class="container d-flex justify-content-center text-center">
  <div class="card shadow-sm w-50 text-bg-light" style="width: 18rem;">
    <img src="https://source.unsplash.com/1000x500/?" class="card-img-top" alt="Picture">
    <div class="card-body">
      <h5 class="card-title fw-bold"><%= @event.title%></h5>
      <h6 class="fw-bold">Number of participants: <%= @count%></h5>
      <br>
      <% @attendees.each_with_index do |att,i| %>
          <p><%= i + 1 %>. <%= User.find(att.user_id).email%></p>
          <br>
      <% end %>
    </div>
    <%= link_to "Edit this event", edit_event_path(@event.id), class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/avatars/create.html.erb
<h1>Avatars#create</h1>
<p>Find me in app/views/avatars/create.html.erb</p>

app/views/checkout/create.js.erb
var stripe = Stripe('<%= Rails.application.credentials.stripe[:public] %>');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function (result) {
  console.log(result.error.message);
});

app/views/events/edit.html.erb
<div class="container d-flex justify-content-center text-center">
  <div class="card shadow-sm w-50 text-bg-light">
    <div class="card-header">
      <div><%= link_to @event.title, event_path(@event.id) %></div>
    </div>
    <div class= "card-body">
      <%= form_with url: event_path(@event.id), method: :patch, local: true do |form| %>
        <p>Description</p>
        <%= form.text_area :description, value: @event.description, size: "70x5" %>
        <br><br>
        <p>Location</p>
        <%= form.text_field :location, value: @event.location %>
        <br><br>
        <p>Price</p>
        <%= form.text_field :price, in: 1..1000, value: @event.price %>
        <br><br>
        <p>Starting date</p>
        <%= form.datetime_local_field :start_date, value: @event.start_date %>
        <br><br>
        <p>Duration</p>
        <%= form.number_field :duration, step: 5 ,value: @event.duration %>
        <br><br>
        <%= form.submit "Accept" %>
      <% end %>
      <br>
      <%= link_to "Delete this event", event_path(@event.id), method: :delete, class: "btn btn-lg btn-primary"%>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<main>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active" aria-current="true"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active carousel-item-start">
        <img src="https://source.unsplash.com/1000x300?event<%= @events.first.title %>" alt="Generic placeholder image" width="100%" >
        <div class="container">
          <div class="carousel-caption text-start">
          <% event = @events.sample %>
            <h1><%= event.title %></h1>
            <p><%= event.description %></p>
            <p><%= link_to "View Event", event_path(event), class: "btn btn-lg btn-primary" %></p>
          </div>
        </div>
      </div>
      <div class="carousel-item carousel-item-next carousel-item-start">
        <img src="https://source.unsplash.com/1000x300?event<%= @events.second.title %>" alt="Generic placeholder image" width="100%" >
        <div class="container">
          <div class="carousel-caption">
          <% event = @events.sample %>
            <h1><%= event.title %></h1>
            <p><%= event.description %></p>
            <p><%= link_to "View Event", event_path(event), class: "btn btn-lg btn-primary" %></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/1000x300?event<%= @events.last.title %>" alt="Generic placeholder image" width="100%" >
        <div class="container">
          <div class="carousel-caption text-end">
          <% event = @events.sample %>
            <h1><%= event.title %></h1>
            <p><%= event.description %></p>
            <p><%= link_to "View Event", event_path(event), class: "btn btn-lg btn-primary" %></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
  <div class="container marketing">
    <!-- Three columns of text below the carousel -->
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-lg-4 event">
          <%= %>
          <img src="https://source.unsplash.com/500x300?event<%= event.title %>" alt=<%event.title%> width="140" height="140">
          <h2 class="fw-normal"><%= event.title %></h2>
          <p><%= event.description %></p>
          <p><%= link_to "View Event", event_path(event.id), class: "btn btn-lg btn-primary" %></p>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/events/new.html.erb
 <div class="container text-center">
  <h3>You want to create a new event? <br> Thank you for making this community a better place!</h3>
  <br>
  <%= form_with url: events_path, local: true do |form| %>
    <p>What title do you want to give your event?</p>
    <%= form.text_field :event_title %>
    <br>
    <br>
    <p>Can you give us some more details?</p>
    <%= form.text_area :event_description, size: "70x5" %>
    <br>
    <br>
    <p>Location</p>
    <%= form.text_field :event_location %>
    <br>
    <br>
    <p>Starting date</p>
    <%= form.datetime_local_field :event_start_date %>
    <br>
    <br>
    <p>How much time is your event gonna last? (increments of 5 minutes only)</p>
    <%= form.number_field :event_duration, step: 5 %>
    <br>
    <br>
    <p>What price ($) will attendees have to pay?</p>
    <%= form.number_field :event_price, in: 1..1000 %>
    <br>
    <br>
    <p>Do you have a picture to show us?</p>
    <%= form.file_field :event_picture %>
    <br>
    <br>
    <%= form.submit "Create Event" %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="col">
    <div class="bs-component">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title text-muted"><%= @event.title %></h5>
          <h6 class="card-subtitle text-muted"><%= @event.admin.first_name %></h6>
        </div>
        <%if @event.event_picture.attached?%>
          <%= image_tag @event.event_picture, alt: 'event_picture' %>
        <%else%>
          <img src="https://source.unsplash.com/1000x500/?" class="card-img-top" alt="Picture">
        <%end%>
        <div class="card-body">
          <p class="card-text text-muted"><%= @event.description %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Place: <%= @event.location %></li>
          <li class="list-group-item">Price: <%= @event.price %></li>
          <li class="list-group-item">Attendees: <%= @count %></li>
          <li class="list-group-item">Contact: <%= @event.admin.email %></li>
        </ul>
        <div class="card-footer text-muted"><%= @event.start_date.strftime("#{@event.start_date.day.ordinalize} %B %Y") %>
        </div>
        <div class="container d-flex justify-content-around">
          <% if @attendance_possible %>
          <%# <div><%= link_to "Attend this event", new_event_attendance_path(@event.id), class: "btn btn-primary" %>
            <div><%= button_to "Book now! (payment)", checkout_index_path, params: {id: @event.id}, remote: true, class: "btn btn-primary" %></div>
          <% end %>
          <% if @event.admin.id == current_user.id || current_user.admin == true %>
            <div><%= link_to "Edit", edit_event_path(@event), class: "btn btn-primary" %></div>
            <div><%= link_to "Show attendees", event_attendances_path(@event.id), class: "btn btn-primary" %></div>
            <div><%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container d-flex justify-content-center text-center">
  <div class="card shadow-sm w-50 text-bg-light">
    <div class="card-header">
      <h4 class="index" href="/user/<%=current_user.id %>">User n° <%= current_user.id %></h4>
    </div>
    <div class= "card-body">
      <%= form_with url: profile_path, method: :post, local: true do |form| %>
        <p>Avatar</p>
        <%= form.file_field :avatar, value:@user.avatar%>
        <br><br>
        <p>First name</p>
        <%= form.text_field :first_name, value: @user.first_name %>
        <br><br>
        <p>Last name</p>
        <%= form.text_field :last_name, value: @user.last_name %>
        <br><br>
        <p>Description</p>
        <%= form.text_field :description, value: @user.description %>
        <br><br>
        <%= form.submit "Accept" %>
      <% end %>
      <br>
      <%= link_to "Click here to change your password", edit_user_registration_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-8 m-auto">
      <div class="bs-component">
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title text-muted"><%= @user.first_name + @user.last_name%></h5>
          </div>
          <%if @user.avatar.attached?%>
            <%= image_tag current_user.avatar, alt: 'avatar' %>
          <%else%>
            <img src="https://source.unsplash.com/1000x500?person" alt="placeholder">
          <%end%>
          <div class="card-body">
            <p class="card-text text-muted"><%= @user.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Email: <%= @user.email %></li>
            <li class="list-group-item">Member since: <%= @user.created_at.strftime("#{@user.created_at.day.ordinalize} %B %Y") %></li>
          </ul>
          <div class="card-footer text-muted">Last updated
            <%= @user.updated_at.strftime("#{@user.updated_at.day.ordinalize} %B %Y") %></div>
          <div class="container d-flex justify-content-center"><%= link_to "Edit", profile_edit_path, class: "btn btn-primary" %></div>
        </div>
      </div>
    </div>
</div>